name: numeric
description: A Class that handles doubles and ints
version: 1.0.4
publish_to: "none"
homepage: https://github.com/RagehAz/numeric.git

environment:
  sdk: ">=2.10.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0

flutter:
